/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      // shorthand of this object is 'intro'
      type: 'doc',
      id: 'intro',
    },
    {
      // shorthand of this object is {'FAQ': [docs]}
      type: 'category',
      label: 'FAQ', 
      items: [
        // cannot use autogenerated here, to hide FAQ entries folders
        'faq/2018-05-06-faq-hs',
        'faq/2018-05-06-faq-hc'
      ]
    },
    {
      'Getting Started': [
        'getting-started/2018-04-28-quick-start'
      ]
    },
    {
      'Tutorials & Training': [
        {
          type: 'autogenerated',
          dirName: 'tutorials'            
        }
      ]
    },
    {
      'Key Concepts: Resources': [
        {
          type: 'autogenerated',
          dirName: 'key-concepts'            
        }
      ]
    },
    {
      'Set up hale»connect': [
        {
          'Create a schema': [
            {
              type: 'autogenerated',
              dirName: 'setup-hc/create-a-schema'            
            }
          ]
        },
        {
          'Create a transformation project': [
            {
              type: 'autogenerated',
              dirName: 'setup-hc/create-a-transformation-project'            
            }
          ]
        },
        {
          'Create a theme': [
            {
              type: 'autogenerated',
              dirName: 'setup-hc/create-a-theme'            
            }
          ]
        },
        {
          'Edit metadata configuration': [
            {
              type: 'autogenerated',
              dirName: 'setup-hc/edit-metadata-config'            
            }
          ]
        }
      ]
    },
    // {
    //   type: 'html',
    //   value: '<img src="sponsor.png" alt="Sidebar Image Item Example" />', // The HTML to be rendered
    //   defaultStyle: true, // Use the default menu item styling
    // },
    // {
    //   type: 'link',
    //   label: '@WeTransform Website', // The link label
    //   href: 'https://www.wetransform.to', // The external URL
    // },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
