name: Label

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - master

jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Apply PR labels
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.LABELER_TOKEN }}"
        sync-labels: true
